run:
  tests: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US
    ignore-words: []

linters:
  disable-all: true
  enable:
    - govet                    # Standard Go vet checks
    - errcheck                 # Check for missing error handling
    - staticcheck              # Advanced static analysis
    - gosimple                 # Simplify complex code
    - ineffassign              # Highlight ineffectual assignments
    - bodyclose                # Ensure HTTP response bodies are closed
    - gofmt                    # Enforce Go formatting
    - gofumpt                  # Stricter formatting than gofmt
    - gosec                    # Check for security vulnerabilities
    - unconvert                # Remove unnecessary type conversions
    - misspell                 # Detect spelling issues in comments
    - lll                      # Detect long lines
    - revive                   # Replacement for golint
    - depguard                 # Restrict certain dependencies
    - unused                   # Replaces structcheck, varcheck, and deadcode

issues:
  exclude-rules:
    - text: "fieldalignment:"
      linters:
        - govet
